name: digitAT
description: digitAT_APp

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  flutter_svg: ^0.19.0
  
  firebase_storage: ^3.1.5
  progress_dialog: ^1.2.2
  provider: ^4.0.1
  url_launcher: ^5.4.11
  flutter_env:
  cached_network_image: ^2.1.0+1
  uuid: ^2.1.0
  video_thumbnail: ^0.2.1
  
  photo_view: ^0.10.2
  video_player: ^0.11.0
  flutter_facebook_login: ^3.0.0
  flutter_webrtc: ^0.3.3
  flutter_ringtone_player: ^2.0.0
  wakelock: 
  firebase_messaging: ^6.0.16
  audio_recorder: ^1.0.2
  audioplayers: ^0.16.1
  permission_handler: ^5.0.1+1
  intl_phone_number_input: 
  pin_code_fields: ^5.2.0
  callkeep: ^0.1.1
  easy_localization: ^2.3.3
  
  shared_preferences: ^0.5.6
  dio: ^3.0.5
  moor_flutter: ^3.1.0
  flutter_multiselect: ^0.5.1
  multiselect_formfield: ^0.1.4
  
  intl: ^0.16.1
  flutter_datetime_picker: ^1.3.8
  dropdown_formfield: ^0.1.2
  image_picker: ^0.6.7+4
  hexcolor: ^1.0.4
  splashscreen: ^1.2.0
  flutter_verification_code_input:
      git:
        url: git://github.com/tinylife-io/flutter_verification_code_input.git
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.6
  carousel_slider: ^1.3.0
  titled_navigation_bar: ^3.6.0
  
  curved_navigation_bar: ^0.1.26
  date_picker_timeline: ^1.2.1
  flutter_chips_input: ^1.8.0
  flutter_typeahead: ^1.8.8

  
  flutter_form_builder: ^3.14.0-alpha.1

  http: ^0.12.0+4
  flutter_counter: ^1.0.3
  stepper_touch:
  gradual_stepper:
  #starflut: ^0.6.0
  google_sign_in: ^4.4.4
  hashtagable:
  
  flutter_bloc: ^3.0.0
  meta: ^1.1.6
  equatable: ^1.0.0
  flutter_screenutil: ^0.7.0
  fluttertoast: ^3.1.0
  flutter_launcher_icons: "^0.7.3"
  paynow: ^1.0.6
  json_annotation: ^3.1.0
  

  flutter_country_picker: ^0.1.6
  mobile_number: ^1.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^3.2.0
  build_runner: ^1.10.0
  json_serializable: ^3.5.0




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
     
    - images/TheLab.png
    - images/HBC.png
    - images/TheLab-grey.png
    - images/microscope-grey.png
    - images/MoneyTel.png
    - images/Hospitals.png
    - images/splash.jpg
    - images/digitAT-white.png
    - images/image-home.jpeg
    - images/facebook-fill.png
    - images/google-fill.png
    - images/cellphone-line.png
    - images/verification.png
    - images/Image23.png
    - images/f1.png
    - images/f-1.png
    - images/undraw_alien_science_nonm.png
    - images/microscope.png
    - images/pill.png
    - images/pill-grey.png
    - images/nurse.png
    - images/nurse-grey.png
    - images/covid19-score.png
    - images/res-rate.png
    - images/pulse.png
    - images/bp.png
    - images/13nov_resize.jpg
    - images/doctor-productivity.jpg
    - images/medical-lab-technician-85654102.jpg
    - images/asset-1.png
    - images/asset-2.png
    - images/asset-3.png
    - images/asset-4.png
    - images/asset-5.png
    - images/asset-6.png
    - images/Image 11.png
    - images/Image 12.png
    - images/Image 19.png
    - images/index.jpeg
    - images/imageuser.png
    - images/gps.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # international:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Bauhaus
      fonts:
        - asset: fonts/Bauhaus 93 Regular.ttf
    - family: LexendDeca
      fonts:
        - asset: fonts/LexendDeca-Regular.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Black.ttf
          weight: 900


